#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: The Hop Ice Cream Cafe
email: hopicecreamcafe@yahoo.com
description: "Scooping ice cream in Asheville, North Carolina since 1978.  The hop offers a wide variety of treats and also hosts fun events."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ee347f
  secondary: ee347f  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: The Hop Merrimon
  pic: 1
  position: The Original Gangsta
  social:
    - title: twitter
      url: https://twitter.com/hopicecream 
    - title: facebook
      url: https://www.facebook.com/TheHopIceCreamCafe 
    - title: instagram
      url: http://instagram.com/hopicecream 

- name: The Hop West
  pic: 2
  position: West Side Playa
  social:
    - title: twitter
      url: https://twitter.com/thehopwest 
    - title: facebook
      url: https://twitter.com/thehopwest 
    - title: instagram
      url: http://instagram.com/thehopwest

- name: The Hop Creamery
  pic: 3
  position: Where Magic Gets Made
  social:
    - title: twitter
      url: https://twitter.com/hopicecreamery 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: tumblr
    url: http://hopicecream.tumblr.com/ 
  - title: youtube
    url: https://www.youtube.com/user/TheHopIceCream 
  - title: pinterest
    url: https://www.pinterest.com/hopicecream/homemade-ice-cream/ 
  - title: instagram
    url: http://instagram.com/hopicecream 
  - title: twitter
    url: https://twitter.com/hopicecream 
  - title: facebook
    url: https://www.facebook.com/TheHopIceCreamCafe 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
